/**
 * @fileoverview gRPC-Web generated client stub for analytics
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: analytics/analytics.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var error_error_pb = require('../error/error_pb.js')
const proto = {};
proto.analytics = require('./analytics_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.analytics.AnalyticsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.analytics.AnalyticsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.TrackStepRequest,
 *   !proto.analytics.TrackStepResponse>}
 */
const methodDescriptor_AnalyticsService_TrackStep = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/TrackStep',
  grpc.web.MethodType.UNARY,
  proto.analytics.TrackStepRequest,
  proto.analytics.TrackStepResponse,
  /**
   * @param {!proto.analytics.TrackStepRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.TrackStepResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.TrackStepRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.TrackStepResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.TrackStepResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.trackStep =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/TrackStep',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_TrackStep,
      callback);
};


/**
 * @param {!proto.analytics.TrackStepRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.TrackStepResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.trackStep =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/TrackStep',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_TrackStep);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.CompleteStepRequest,
 *   !proto.analytics.CompleteStepResponse>}
 */
const methodDescriptor_AnalyticsService_CompleteStep = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/CompleteStep',
  grpc.web.MethodType.UNARY,
  proto.analytics.CompleteStepRequest,
  proto.analytics.CompleteStepResponse,
  /**
   * @param {!proto.analytics.CompleteStepRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.CompleteStepResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.CompleteStepRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.CompleteStepResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.CompleteStepResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.completeStep =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/CompleteStep',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_CompleteStep,
      callback);
};


/**
 * @param {!proto.analytics.CompleteStepRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.CompleteStepResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.completeStep =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/CompleteStep',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_CompleteStep);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.GetRegistrationStepsRequest,
 *   !proto.analytics.GetRegistrationStepsResponse>}
 */
const methodDescriptor_AnalyticsService_GetRegistrationSteps = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/GetRegistrationSteps',
  grpc.web.MethodType.UNARY,
  proto.analytics.GetRegistrationStepsRequest,
  proto.analytics.GetRegistrationStepsResponse,
  /**
   * @param {!proto.analytics.GetRegistrationStepsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.GetRegistrationStepsResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.GetRegistrationStepsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.GetRegistrationStepsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.GetRegistrationStepsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.getRegistrationSteps =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/GetRegistrationSteps',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetRegistrationSteps,
      callback);
};


/**
 * @param {!proto.analytics.GetRegistrationStepsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.GetRegistrationStepsResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.getRegistrationSteps =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/GetRegistrationSteps',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetRegistrationSteps);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.GetUserJourneyRequest,
 *   !proto.analytics.GetUserJourneyResponse>}
 */
const methodDescriptor_AnalyticsService_GetUserJourney = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/GetUserJourney',
  grpc.web.MethodType.UNARY,
  proto.analytics.GetUserJourneyRequest,
  proto.analytics.GetUserJourneyResponse,
  /**
   * @param {!proto.analytics.GetUserJourneyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.GetUserJourneyResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.GetUserJourneyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.GetUserJourneyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.GetUserJourneyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.getUserJourney =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/GetUserJourney',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetUserJourney,
      callback);
};


/**
 * @param {!proto.analytics.GetUserJourneyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.GetUserJourneyResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.getUserJourney =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/GetUserJourney',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetUserJourney);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.GetAllSessionsRequest,
 *   !proto.analytics.GetAllSessionsResponse>}
 */
const methodDescriptor_AnalyticsService_GetAllSessions = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/GetAllSessions',
  grpc.web.MethodType.UNARY,
  proto.analytics.GetAllSessionsRequest,
  proto.analytics.GetAllSessionsResponse,
  /**
   * @param {!proto.analytics.GetAllSessionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.GetAllSessionsResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.GetAllSessionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.GetAllSessionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.GetAllSessionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.getAllSessions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/GetAllSessions',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetAllSessions,
      callback);
};


/**
 * @param {!proto.analytics.GetAllSessionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.GetAllSessionsResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.getAllSessions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/GetAllSessions',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetAllSessions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.GetSessionJourneyRequest,
 *   !proto.analytics.GetSessionJourneyResponse>}
 */
const methodDescriptor_AnalyticsService_GetSessionJourney = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/GetSessionJourney',
  grpc.web.MethodType.UNARY,
  proto.analytics.GetSessionJourneyRequest,
  proto.analytics.GetSessionJourneyResponse,
  /**
   * @param {!proto.analytics.GetSessionJourneyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.GetSessionJourneyResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.GetSessionJourneyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.GetSessionJourneyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.GetSessionJourneyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.getSessionJourney =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/GetSessionJourney',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetSessionJourney,
      callback);
};


/**
 * @param {!proto.analytics.GetSessionJourneyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.GetSessionJourneyResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.getSessionJourney =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/GetSessionJourney',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetSessionJourney);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.GetRegistrationStatsRequest,
 *   !proto.analytics.GetRegistrationStatsResponse>}
 */
const methodDescriptor_AnalyticsService_GetRegistrationStats = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/GetRegistrationStats',
  grpc.web.MethodType.UNARY,
  proto.analytics.GetRegistrationStatsRequest,
  proto.analytics.GetRegistrationStatsResponse,
  /**
   * @param {!proto.analytics.GetRegistrationStatsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.GetRegistrationStatsResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.GetRegistrationStatsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.GetRegistrationStatsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.GetRegistrationStatsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.getRegistrationStats =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/GetRegistrationStats',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetRegistrationStats,
      callback);
};


/**
 * @param {!proto.analytics.GetRegistrationStatsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.GetRegistrationStatsResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.getRegistrationStats =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/GetRegistrationStats',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetRegistrationStats);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.TrackVerificationRequestRequest,
 *   !proto.analytics.TrackVerificationRequestResponse>}
 */
const methodDescriptor_AnalyticsService_TrackVerificationRequest = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/TrackVerificationRequest',
  grpc.web.MethodType.UNARY,
  proto.analytics.TrackVerificationRequestRequest,
  proto.analytics.TrackVerificationRequestResponse,
  /**
   * @param {!proto.analytics.TrackVerificationRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.TrackVerificationRequestResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.TrackVerificationRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.TrackVerificationRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.TrackVerificationRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.trackVerificationRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/TrackVerificationRequest',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_TrackVerificationRequest,
      callback);
};


/**
 * @param {!proto.analytics.TrackVerificationRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.TrackVerificationRequestResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.trackVerificationRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/TrackVerificationRequest',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_TrackVerificationRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.MarkVerificationCompleteRequest,
 *   !proto.analytics.MarkVerificationCompleteResponse>}
 */
const methodDescriptor_AnalyticsService_MarkVerificationComplete = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/MarkVerificationComplete',
  grpc.web.MethodType.UNARY,
  proto.analytics.MarkVerificationCompleteRequest,
  proto.analytics.MarkVerificationCompleteResponse,
  /**
   * @param {!proto.analytics.MarkVerificationCompleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.MarkVerificationCompleteResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.MarkVerificationCompleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.MarkVerificationCompleteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.MarkVerificationCompleteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.markVerificationComplete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/MarkVerificationComplete',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_MarkVerificationComplete,
      callback);
};


/**
 * @param {!proto.analytics.MarkVerificationCompleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.MarkVerificationCompleteResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.markVerificationComplete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/MarkVerificationComplete',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_MarkVerificationComplete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.GetVerificationStatusRequest,
 *   !proto.analytics.GetVerificationStatusResponse>}
 */
const methodDescriptor_AnalyticsService_GetVerificationStatus = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/GetVerificationStatus',
  grpc.web.MethodType.UNARY,
  proto.analytics.GetVerificationStatusRequest,
  proto.analytics.GetVerificationStatusResponse,
  /**
   * @param {!proto.analytics.GetVerificationStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.GetVerificationStatusResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.GetVerificationStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.GetVerificationStatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.GetVerificationStatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.getVerificationStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/GetVerificationStatus',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetVerificationStatus,
      callback);
};


/**
 * @param {!proto.analytics.GetVerificationStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.GetVerificationStatusResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.getVerificationStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/GetVerificationStatus',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_GetVerificationStatus);
};


module.exports = proto.analytics;

