AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An AWS lambda function to create an org (business or beneficiary)

Globals:
  Function:
    Environment:
      Variables:
        DB_HOST:
        DB_NAME:
        DB_USER:
        DB_PASSWORD:
    Timeout: 3


Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Description: python code to create org in database
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /register/appOrg
            Method: post
