// source: beneficiary/beneficiary.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var error_error_pb = require('../error/error_pb.js');
goog.object.extend(proto, error_error_pb);
goog.exportSymbol('proto.beneficiary.Beneficiary', null, global);
goog.exportSymbol('proto.beneficiary.CreateBeneficiaryRequest', null, global);
goog.exportSymbol('proto.beneficiary.CreateBeneficiaryResponse', null, global);
goog.exportSymbol('proto.beneficiary.GetBeneficiaryRequest', null, global);
goog.exportSymbol('proto.beneficiary.GetBeneficiaryResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.beneficiary.Beneficiary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.beneficiary.Beneficiary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.beneficiary.Beneficiary.displayName = 'proto.beneficiary.Beneficiary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.beneficiary.GetBeneficiaryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.beneficiary.GetBeneficiaryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.beneficiary.GetBeneficiaryRequest.displayName = 'proto.beneficiary.GetBeneficiaryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.beneficiary.GetBeneficiaryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.beneficiary.GetBeneficiaryResponse.repeatedFields_, null);
};
goog.inherits(proto.beneficiary.GetBeneficiaryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.beneficiary.GetBeneficiaryResponse.displayName = 'proto.beneficiary.GetBeneficiaryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.beneficiary.CreateBeneficiaryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.beneficiary.CreateBeneficiaryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.beneficiary.CreateBeneficiaryRequest.displayName = 'proto.beneficiary.CreateBeneficiaryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.beneficiary.CreateBeneficiaryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.beneficiary.CreateBeneficiaryResponse.repeatedFields_, null);
};
goog.inherits(proto.beneficiary.CreateBeneficiaryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.beneficiary.CreateBeneficiaryResponse.displayName = 'proto.beneficiary.CreateBeneficiaryResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.beneficiary.Beneficiary.prototype.toObject = function(opt_includeInstance) {
  return proto.beneficiary.Beneficiary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.beneficiary.Beneficiary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.Beneficiary.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    beneficiaryName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    email: jspb.Message.getFieldWithDefault(msg, 3, ""),
    websiteUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    phoneNumber: jspb.Message.getFieldWithDefault(msg, 5, ""),
    locationCity: jspb.Message.getFieldWithDefault(msg, 6, ""),
    locationState: jspb.Message.getFieldWithDefault(msg, 7, ""),
    ein: jspb.Message.getFieldWithDefault(msg, 8, ""),
    beneficiaryDescription: jspb.Message.getFieldWithDefault(msg, 9, ""),
    beneficiarySize: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.beneficiary.Beneficiary}
 */
proto.beneficiary.Beneficiary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.beneficiary.Beneficiary;
  return proto.beneficiary.Beneficiary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.beneficiary.Beneficiary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.beneficiary.Beneficiary}
 */
proto.beneficiary.Beneficiary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiaryName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWebsiteUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoneNumber(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocationCity(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocationState(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setEin(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiaryDescription(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiarySize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.beneficiary.Beneficiary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.beneficiary.Beneficiary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.beneficiary.Beneficiary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.Beneficiary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBeneficiaryName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWebsiteUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLocationCity();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLocationState();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEin();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getBeneficiaryDescription();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getBeneficiarySize();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string beneficiary_name = 2;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getBeneficiaryName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setBeneficiaryName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string website_url = 4;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getWebsiteUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setWebsiteUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string phone_number = 5;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setPhoneNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string location_city = 6;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getLocationCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setLocationCity = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string location_state = 7;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getLocationState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setLocationState = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string ein = 8;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getEin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setEin = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string beneficiary_description = 9;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getBeneficiaryDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setBeneficiaryDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string beneficiary_size = 10;
 * @return {string}
 */
proto.beneficiary.Beneficiary.prototype.getBeneficiarySize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.Beneficiary} returns this
 */
proto.beneficiary.Beneficiary.prototype.setBeneficiarySize = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.beneficiary.GetBeneficiaryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.beneficiary.GetBeneficiaryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.beneficiary.GetBeneficiaryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.GetBeneficiaryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    beneficiaryId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.beneficiary.GetBeneficiaryRequest}
 */
proto.beneficiary.GetBeneficiaryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.beneficiary.GetBeneficiaryRequest;
  return proto.beneficiary.GetBeneficiaryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.beneficiary.GetBeneficiaryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.beneficiary.GetBeneficiaryRequest}
 */
proto.beneficiary.GetBeneficiaryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiaryId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.beneficiary.GetBeneficiaryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.beneficiary.GetBeneficiaryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.beneficiary.GetBeneficiaryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.GetBeneficiaryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBeneficiaryId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string beneficiary_id = 1;
 * @return {string}
 */
proto.beneficiary.GetBeneficiaryRequest.prototype.getBeneficiaryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.GetBeneficiaryRequest} returns this
 */
proto.beneficiary.GetBeneficiaryRequest.prototype.setBeneficiaryId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.beneficiary.GetBeneficiaryResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.beneficiary.GetBeneficiaryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.beneficiary.GetBeneficiaryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.GetBeneficiaryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    beneficiary: (f = msg.getBeneficiary()) && proto.beneficiary.Beneficiary.toObject(includeInstance, f),
    errorsList: jspb.Message.toObjectList(msg.getErrorsList(),
    error_error_pb.Error.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.beneficiary.GetBeneficiaryResponse}
 */
proto.beneficiary.GetBeneficiaryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.beneficiary.GetBeneficiaryResponse;
  return proto.beneficiary.GetBeneficiaryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.beneficiary.GetBeneficiaryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.beneficiary.GetBeneficiaryResponse}
 */
proto.beneficiary.GetBeneficiaryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.beneficiary.Beneficiary;
      reader.readMessage(value,proto.beneficiary.Beneficiary.deserializeBinaryFromReader);
      msg.setBeneficiary(value);
      break;
    case 2:
      var value = new error_error_pb.Error;
      reader.readMessage(value,error_error_pb.Error.deserializeBinaryFromReader);
      msg.addErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.beneficiary.GetBeneficiaryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.beneficiary.GetBeneficiaryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.GetBeneficiaryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBeneficiary();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.beneficiary.Beneficiary.serializeBinaryToWriter
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      error_error_pb.Error.serializeBinaryToWriter
    );
  }
};


/**
 * optional Beneficiary beneficiary = 1;
 * @return {?proto.beneficiary.Beneficiary}
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.getBeneficiary = function() {
  return /** @type{?proto.beneficiary.Beneficiary} */ (
    jspb.Message.getWrapperField(this, proto.beneficiary.Beneficiary, 1));
};


/**
 * @param {?proto.beneficiary.Beneficiary|undefined} value
 * @return {!proto.beneficiary.GetBeneficiaryResponse} returns this
*/
proto.beneficiary.GetBeneficiaryResponse.prototype.setBeneficiary = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.beneficiary.GetBeneficiaryResponse} returns this
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.clearBeneficiary = function() {
  return this.setBeneficiary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.hasBeneficiary = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated error.Error errors = 2;
 * @return {!Array<!proto.error.Error>}
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.getErrorsList = function() {
  return /** @type{!Array<!proto.error.Error>} */ (
    jspb.Message.getRepeatedWrapperField(this, error_error_pb.Error, 2));
};


/**
 * @param {!Array<!proto.error.Error>} value
 * @return {!proto.beneficiary.GetBeneficiaryResponse} returns this
*/
proto.beneficiary.GetBeneficiaryResponse.prototype.setErrorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.error.Error=} opt_value
 * @param {number=} opt_index
 * @return {!proto.error.Error}
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.addErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.error.Error, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.beneficiary.GetBeneficiaryResponse} returns this
 */
proto.beneficiary.GetBeneficiaryResponse.prototype.clearErrorsList = function() {
  return this.setErrorsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.beneficiary.CreateBeneficiaryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.beneficiary.CreateBeneficiaryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.CreateBeneficiaryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    beneficiaryName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    websiteUrl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    phoneNumber: jspb.Message.getFieldWithDefault(msg, 4, ""),
    locationCity: jspb.Message.getFieldWithDefault(msg, 5, ""),
    locationState: jspb.Message.getFieldWithDefault(msg, 6, ""),
    ein: jspb.Message.getFieldWithDefault(msg, 7, ""),
    beneficiaryDescription: jspb.Message.getFieldWithDefault(msg, 8, ""),
    beneficiarySize: jspb.Message.getFieldWithDefault(msg, 9, ""),
    userEmail: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.beneficiary.CreateBeneficiaryRequest}
 */
proto.beneficiary.CreateBeneficiaryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.beneficiary.CreateBeneficiaryRequest;
  return proto.beneficiary.CreateBeneficiaryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.beneficiary.CreateBeneficiaryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.beneficiary.CreateBeneficiaryRequest}
 */
proto.beneficiary.CreateBeneficiaryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiaryName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWebsiteUrl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoneNumber(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocationCity(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocationState(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setEin(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiaryDescription(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiarySize(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.beneficiary.CreateBeneficiaryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.beneficiary.CreateBeneficiaryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.CreateBeneficiaryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBeneficiaryName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWebsiteUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLocationCity();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLocationState();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEin();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getBeneficiaryDescription();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getBeneficiarySize();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getUserEmail();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string beneficiary_name = 1;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getBeneficiaryName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setBeneficiaryName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string website_url = 3;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getWebsiteUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setWebsiteUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string phone_number = 4;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setPhoneNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string location_city = 5;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getLocationCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setLocationCity = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string location_state = 6;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getLocationState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setLocationState = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string ein = 7;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getEin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setEin = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string beneficiary_description = 8;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getBeneficiaryDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setBeneficiaryDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string beneficiary_size = 9;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getBeneficiarySize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setBeneficiarySize = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string user_email = 10;
 * @return {string}
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.getUserEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.beneficiary.CreateBeneficiaryRequest} returns this
 */
proto.beneficiary.CreateBeneficiaryRequest.prototype.setUserEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.beneficiary.CreateBeneficiaryResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.beneficiary.CreateBeneficiaryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.beneficiary.CreateBeneficiaryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.CreateBeneficiaryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    beneficiary: (f = msg.getBeneficiary()) && proto.beneficiary.Beneficiary.toObject(includeInstance, f),
    errorsList: jspb.Message.toObjectList(msg.getErrorsList(),
    error_error_pb.Error.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.beneficiary.CreateBeneficiaryResponse}
 */
proto.beneficiary.CreateBeneficiaryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.beneficiary.CreateBeneficiaryResponse;
  return proto.beneficiary.CreateBeneficiaryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.beneficiary.CreateBeneficiaryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.beneficiary.CreateBeneficiaryResponse}
 */
proto.beneficiary.CreateBeneficiaryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.beneficiary.Beneficiary;
      reader.readMessage(value,proto.beneficiary.Beneficiary.deserializeBinaryFromReader);
      msg.setBeneficiary(value);
      break;
    case 2:
      var value = new error_error_pb.Error;
      reader.readMessage(value,error_error_pb.Error.deserializeBinaryFromReader);
      msg.addErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.beneficiary.CreateBeneficiaryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.beneficiary.CreateBeneficiaryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.beneficiary.CreateBeneficiaryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBeneficiary();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.beneficiary.Beneficiary.serializeBinaryToWriter
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      error_error_pb.Error.serializeBinaryToWriter
    );
  }
};


/**
 * optional Beneficiary beneficiary = 1;
 * @return {?proto.beneficiary.Beneficiary}
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.getBeneficiary = function() {
  return /** @type{?proto.beneficiary.Beneficiary} */ (
    jspb.Message.getWrapperField(this, proto.beneficiary.Beneficiary, 1));
};


/**
 * @param {?proto.beneficiary.Beneficiary|undefined} value
 * @return {!proto.beneficiary.CreateBeneficiaryResponse} returns this
*/
proto.beneficiary.CreateBeneficiaryResponse.prototype.setBeneficiary = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.beneficiary.CreateBeneficiaryResponse} returns this
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.clearBeneficiary = function() {
  return this.setBeneficiary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.hasBeneficiary = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated error.Error errors = 2;
 * @return {!Array<!proto.error.Error>}
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.getErrorsList = function() {
  return /** @type{!Array<!proto.error.Error>} */ (
    jspb.Message.getRepeatedWrapperField(this, error_error_pb.Error, 2));
};


/**
 * @param {!Array<!proto.error.Error>} value
 * @return {!proto.beneficiary.CreateBeneficiaryResponse} returns this
*/
proto.beneficiary.CreateBeneficiaryResponse.prototype.setErrorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.error.Error=} opt_value
 * @param {number=} opt_index
 * @return {!proto.error.Error}
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.addErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.error.Error, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.beneficiary.CreateBeneficiaryResponse} returns this
 */
proto.beneficiary.CreateBeneficiaryResponse.prototype.clearErrorsList = function() {
  return this.setErrorsList([]);
};


goog.object.extend(exports, proto.beneficiary);
