/**
 * @fileoverview gRPC-Web generated client stub for beneficiary
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: beneficiary/beneficiary.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var error_error_pb = require('../error/error_pb.js')
const proto = {};
proto.beneficiary = require('./beneficiary_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.beneficiary.BeneficiaryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.beneficiary.BeneficiaryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.beneficiary.GetBeneficiaryRequest,
 *   !proto.beneficiary.GetBeneficiaryResponse>}
 */
const methodDescriptor_BeneficiaryService_GetBeneficiary = new grpc.web.MethodDescriptor(
  '/beneficiary.BeneficiaryService/GetBeneficiary',
  grpc.web.MethodType.UNARY,
  proto.beneficiary.GetBeneficiaryRequest,
  proto.beneficiary.GetBeneficiaryResponse,
  /**
   * @param {!proto.beneficiary.GetBeneficiaryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.beneficiary.GetBeneficiaryResponse.deserializeBinary
);


/**
 * @param {!proto.beneficiary.GetBeneficiaryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.beneficiary.GetBeneficiaryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.beneficiary.GetBeneficiaryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.beneficiary.BeneficiaryServiceClient.prototype.getBeneficiary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/beneficiary.BeneficiaryService/GetBeneficiary',
      request,
      metadata || {},
      methodDescriptor_BeneficiaryService_GetBeneficiary,
      callback);
};


/**
 * @param {!proto.beneficiary.GetBeneficiaryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.beneficiary.GetBeneficiaryResponse>}
 *     Promise that resolves to the response
 */
proto.beneficiary.BeneficiaryServicePromiseClient.prototype.getBeneficiary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/beneficiary.BeneficiaryService/GetBeneficiary',
      request,
      metadata || {},
      methodDescriptor_BeneficiaryService_GetBeneficiary);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.beneficiary.CreateBeneficiaryRequest,
 *   !proto.beneficiary.CreateBeneficiaryResponse>}
 */
const methodDescriptor_BeneficiaryService_CreateBeneficiary = new grpc.web.MethodDescriptor(
  '/beneficiary.BeneficiaryService/CreateBeneficiary',
  grpc.web.MethodType.UNARY,
  proto.beneficiary.CreateBeneficiaryRequest,
  proto.beneficiary.CreateBeneficiaryResponse,
  /**
   * @param {!proto.beneficiary.CreateBeneficiaryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.beneficiary.CreateBeneficiaryResponse.deserializeBinary
);


/**
 * @param {!proto.beneficiary.CreateBeneficiaryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.beneficiary.CreateBeneficiaryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.beneficiary.CreateBeneficiaryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.beneficiary.BeneficiaryServiceClient.prototype.createBeneficiary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/beneficiary.BeneficiaryService/CreateBeneficiary',
      request,
      metadata || {},
      methodDescriptor_BeneficiaryService_CreateBeneficiary,
      callback);
};


/**
 * @param {!proto.beneficiary.CreateBeneficiaryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.beneficiary.CreateBeneficiaryResponse>}
 *     Promise that resolves to the response
 */
proto.beneficiary.BeneficiaryServicePromiseClient.prototype.createBeneficiary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/beneficiary.BeneficiaryService/CreateBeneficiary',
      request,
      metadata || {},
      methodDescriptor_BeneficiaryService_CreateBeneficiary);
};


module.exports = proto.beneficiary;

