/**
 * @fileoverview gRPC-Web generated client stub for business
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: business/business.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var error_error_pb = require('../error/error_pb.js')
const proto = {};
proto.business = require('./business_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.business.BusinessServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.business.BusinessServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.GetBusinessRequest,
 *   !proto.business.GetBusinessResponse>}
 */
const methodDescriptor_BusinessService_GetBusiness = new grpc.web.MethodDescriptor(
  '/business.BusinessService/GetBusiness',
  grpc.web.MethodType.UNARY,
  proto.business.GetBusinessRequest,
  proto.business.GetBusinessResponse,
  /**
   * @param {!proto.business.GetBusinessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.GetBusinessResponse.deserializeBinary
);


/**
 * @param {!proto.business.GetBusinessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.GetBusinessResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.GetBusinessResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.BusinessServiceClient.prototype.getBusiness =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.BusinessService/GetBusiness',
      request,
      metadata || {},
      methodDescriptor_BusinessService_GetBusiness,
      callback);
};


/**
 * @param {!proto.business.GetBusinessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.GetBusinessResponse>}
 *     Promise that resolves to the response
 */
proto.business.BusinessServicePromiseClient.prototype.getBusiness =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.BusinessService/GetBusiness',
      request,
      metadata || {},
      methodDescriptor_BusinessService_GetBusiness);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.CreateBusinessRequest,
 *   !proto.business.CreateBusinessResponse>}
 */
const methodDescriptor_BusinessService_CreateBusiness = new grpc.web.MethodDescriptor(
  '/business.BusinessService/CreateBusiness',
  grpc.web.MethodType.UNARY,
  proto.business.CreateBusinessRequest,
  proto.business.CreateBusinessResponse,
  /**
   * @param {!proto.business.CreateBusinessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.CreateBusinessResponse.deserializeBinary
);


/**
 * @param {!proto.business.CreateBusinessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.CreateBusinessResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.CreateBusinessResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.BusinessServiceClient.prototype.createBusiness =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.BusinessService/CreateBusiness',
      request,
      metadata || {},
      methodDescriptor_BusinessService_CreateBusiness,
      callback);
};


/**
 * @param {!proto.business.CreateBusinessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.CreateBusinessResponse>}
 *     Promise that resolves to the response
 */
proto.business.BusinessServicePromiseClient.prototype.createBusiness =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.BusinessService/CreateBusiness',
      request,
      metadata || {},
      methodDescriptor_BusinessService_CreateBusiness);
};


module.exports = proto.business;

