version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy-grpc-proxy
    ports:
      - "8080:8080"  # gRPC-Web endpoint
      - "9901:9901"  # Admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - asante-network
    extra_hosts:
      # Allow Envoy to reach services on host machine
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9901/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  asante-network:
    external: true
    name: asante-network