# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beneficiary/beneficiary.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codegen.error import error_pb2 as error_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62\x65neficiary/beneficiary.proto\x12\x0b\x62\x65neficiary\x1a\x11\x65rror/error.proto\"\xe4\x01\n\x0b\x42\x65neficiary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10\x62\x65neficiary_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x13\n\x0bwebsite_url\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\x12\x15\n\rlocation_city\x18\x06 \x01(\t\x12\x16\n\x0elocation_state\x18\x07 \x01(\t\x12\x0b\n\x03\x65in\x18\x08 \x01(\t\x12\x1f\n\x17\x62\x65neficiary_description\x18\t \x01(\t\x12\x18\n\x10\x62\x65neficiary_size\x18\n \x01(\t\"/\n\x15GetBeneficiaryRequest\x12\x16\n\x0e\x62\x65neficiary_id\x18\x01 \x01(\t\"e\n\x16GetBeneficiaryResponse\x12-\n\x0b\x62\x65neficiary\x18\x01 \x01(\x0b\x32\x18.beneficiary.Beneficiary\x12\x1c\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x0c.error.Error\"\xf9\x01\n\x18\x43reateBeneficiaryRequest\x12\x18\n\x10\x62\x65neficiary_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x13\n\x0bwebsite_url\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x15\n\rlocation_city\x18\x05 \x01(\t\x12\x16\n\x0elocation_state\x18\x06 \x01(\t\x12\x0b\n\x03\x65in\x18\x07 \x01(\t\x12\x1f\n\x17\x62\x65neficiary_description\x18\x08 \x01(\t\x12\x18\n\x10\x62\x65neficiary_size\x18\t \x01(\t\x12\x12\n\nuser_email\x18\n \x01(\t\"h\n\x19\x43reateBeneficiaryResponse\x12-\n\x0b\x62\x65neficiary\x18\x01 \x01(\x0b\x32\x18.beneficiary.Beneficiary\x12\x1c\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x0c.error.Error2\xd3\x01\n\x12\x42\x65neficiaryService\x12Y\n\x0eGetBeneficiary\x12\".beneficiary.GetBeneficiaryRequest\x1a#.beneficiary.GetBeneficiaryResponse\x12\x62\n\x11\x43reateBeneficiary\x12%.beneficiary.CreateBeneficiaryRequest\x1a&.beneficiary.CreateBeneficiaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beneficiary.beneficiary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BENEFICIARY']._serialized_start=66
  _globals['_BENEFICIARY']._serialized_end=294
  _globals['_GETBENEFICIARYREQUEST']._serialized_start=296
  _globals['_GETBENEFICIARYREQUEST']._serialized_end=343
  _globals['_GETBENEFICIARYRESPONSE']._serialized_start=345
  _globals['_GETBENEFICIARYRESPONSE']._serialized_end=446
  _globals['_CREATEBENEFICIARYREQUEST']._serialized_start=449
  _globals['_CREATEBENEFICIARYREQUEST']._serialized_end=698
  _globals['_CREATEBENEFICIARYRESPONSE']._serialized_start=700
  _globals['_CREATEBENEFICIARYRESPONSE']._serialized_end=804
  _globals['_BENEFICIARYSERVICE']._serialized_start=807
  _globals['_BENEFICIARYSERVICE']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
