# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/entity_type.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth/entity_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61uth/entity_type.proto\x12\x0c\x61\x63\x63ount.auth*f\n\nEntityType\x12\x16\n\x12\x45NTITY_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x45NTITY_BUSINESS\x10\x01\x12\x16\n\x12\x45NTITY_BENEFICIARY\x10\x02\x12\x13\n\x0f\x45NTITY_CONSUMER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.entity_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYTYPE']._serialized_start=40
  _globals['_ENTITYTYPE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
