# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from codegen.beneficiary import beneficiary_pb2 as beneficiary_dot_beneficiary__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in beneficiary/beneficiary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BeneficiaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBeneficiary = channel.unary_unary(
                '/beneficiary.BeneficiaryService/GetBeneficiary',
                request_serializer=beneficiary_dot_beneficiary__pb2.GetBeneficiaryRequest.SerializeToString,
                response_deserializer=beneficiary_dot_beneficiary__pb2.GetBeneficiaryResponse.FromString,
                _registered_method=True)
        self.CreateBeneficiary = channel.unary_unary(
                '/beneficiary.BeneficiaryService/CreateBeneficiary',
                request_serializer=beneficiary_dot_beneficiary__pb2.CreateBeneficiaryRequest.SerializeToString,
                response_deserializer=beneficiary_dot_beneficiary__pb2.CreateBeneficiaryResponse.FromString,
                _registered_method=True)


class BeneficiaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBeneficiary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBeneficiary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeneficiaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBeneficiary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBeneficiary,
                    request_deserializer=beneficiary_dot_beneficiary__pb2.GetBeneficiaryRequest.FromString,
                    response_serializer=beneficiary_dot_beneficiary__pb2.GetBeneficiaryResponse.SerializeToString,
            ),
            'CreateBeneficiary': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBeneficiary,
                    request_deserializer=beneficiary_dot_beneficiary__pb2.CreateBeneficiaryRequest.FromString,
                    response_serializer=beneficiary_dot_beneficiary__pb2.CreateBeneficiaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beneficiary.BeneficiaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beneficiary.BeneficiaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BeneficiaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBeneficiary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beneficiary.BeneficiaryService/GetBeneficiary',
            beneficiary_dot_beneficiary__pb2.GetBeneficiaryRequest.SerializeToString,
            beneficiary_dot_beneficiary__pb2.GetBeneficiaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBeneficiary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beneficiary.BeneficiaryService/CreateBeneficiary',
            beneficiary_dot_beneficiary__pb2.CreateBeneficiaryRequest.SerializeToString,
            beneficiary_dot_beneficiary__pb2.CreateBeneficiaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
