# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error/error.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'error/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65rror/error.proto\x12\x05\x65rror\"H\n\x05\x45rror\x12\x1e\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x10.error.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t*\x95\x01\n\tErrorCode\x12\x0e\n\nERROR_NONE\x10\x00\x12\x1b\n\x17\x45RROR_INVALID_PARAMETER\x10\x01\x12\x13\n\x0f\x45RROR_NOT_FOUND\x10\x02\x12\x18\n\x14\x45RROR_ALREADY_EXISTS\x10\x03\x12\x18\n\x14\x45RROR_DATABASE_ERROR\x10\x04\x12\x12\n\x0e\x45RROR_INTERNAL\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=103
  _globals['_ERRORCODE']._serialized_end=252
  _globals['_ERROR']._serialized_start=28
  _globals['_ERROR']._serialized_end=100
# @@protoc_insertion_point(module_scope)
