-- privileges for default user in development environment

-- This script will be executed when the PostgreSQL container is first created

-- Grant comprehensive privileges to the default user
-- First, grant all privileges on database
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};

-- Connect to the specific database to grant schema-level permissions
\connect ${POSTGRES_DB}

-- Make user a superuser for development purposes
-- This allows full control over all database objects
ALTER USER ${POSTGRES_USER} WITH SUPERUSER;

-- Grant permissions to create schemas
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};

-- For public schema (created by default)
GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON ALL TYPES IN SCHEMA public TO ${POSTGRES_USER};

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON PROCEDURES TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TYPES TO ${POSTGRES_USER};

-- Grant specific privileges needed for triggers and stored procedures
GRANT TRIGGER ON ALL TABLES IN SCHEMA public TO ${POSTGRES_USER};
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ${POSTGRES_USER};
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO ${POSTGRES_USER};

-- Ensure user has privileges for future triggers
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT TRIGGER ON TABLES TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT EXECUTE ON PROCEDURES TO ${POSTGRES_USER};

-- Grant usage on all sequences (for serial/identity columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_USER};
