name: account_manager

services:
  # Resource Services
  create_resource:
    build:
      context: .
      dockerfile: ./src/features/resource/create_resource/Dockerfile
    image: account_manager_dev/create_resource
    container_name: create_resource
    ports:
      - "60000:60000"
    environment:
      - PYTHONPATH=/app
    networks:
      - asante-network
    profiles:
      - dev
      - test
      - resource

  # integration-tests:
  #   build:
  #     context: .
  #     dockerfile: ./tests/integration/Dockerfile
  #   container_name: account-manager-integration-tests
  #   ports:
  #     - "40000:40000"
  #   environment:
  #     - PYTHONPATH=/app
  #     - STARTUP_DELAY=15
  #   networks:
  #     - asante-network
  #   depends_on:
  #     create_resource:
  #       condition: service_healthy
  #   command: >
  #     python /app/tools/tests/run_integration_tests.py
  #   profiles:
  #     - test

networks:
  asante-network:
    external: true
    driver: bridge
    name: asante-network
