# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/create_user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user/create_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from auth import auth_pb2 as auth_dot_auth__pb2
from error import user_error_pb2 as error_dot_user__error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16user/create_user.proto\x12\x11user.user_service\x1a\x0f\x61uth/auth.proto\x1a\x16\x65rror/user_error.proto\"\xbf\x01\n\x11\x43reateUserRequest\x12\x1d\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x0f.user.auth.Auth\x12@\n\tuser_data\x18\x02 \x01(\x0b\x32-.user.user_service.CreateUserRequest.UserData\x1aI\n\x08UserData\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tuser_type\x18\x02 \x01(\t\x12\x1b\n\x13mailing_list_signup\x18\x03 \x01(\x08\"\xab\x01\n\x12\x43reateUserResponse\x12\x38\n\x04user\x18\x01 \x01(\x0b\x32*.user.user_service.CreateUserResponse.User\x12%\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x15.user.error.UserError\x1a\x34\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tuser_type\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.create_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=87
  _globals['_CREATEUSERREQUEST']._serialized_end=278
  _globals['_CREATEUSERREQUEST_USERDATA']._serialized_start=205
  _globals['_CREATEUSERREQUEST_USERDATA']._serialized_end=278
  _globals['_CREATEUSERRESPONSE']._serialized_start=281
  _globals['_CREATEUSERRESPONSE']._serialized_end=452
  _globals['_CREATEUSERRESPONSE_USER']._serialized_start=400
  _globals['_CREATEUSERRESPONSE_USER']._serialized_end=452
# @@protoc_insertion_point(module_scope)
