# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from codegen.analytics import analytics_pb2 as analytics_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analytics/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackStep = channel.unary_unary(
                '/analytics.AnalyticsService/TrackStep',
                request_serializer=analytics_dot_analytics__pb2.TrackStepRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.TrackStepResponse.FromString,
                _registered_method=True)
        self.CompleteStep = channel.unary_unary(
                '/analytics.AnalyticsService/CompleteStep',
                request_serializer=analytics_dot_analytics__pb2.CompleteStepRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.CompleteStepResponse.FromString,
                _registered_method=True)
        self.GetRegistrationSteps = channel.unary_unary(
                '/analytics.AnalyticsService/GetRegistrationSteps',
                request_serializer=analytics_dot_analytics__pb2.GetRegistrationStepsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.GetRegistrationStepsResponse.FromString,
                _registered_method=True)
        self.GetUserJourney = channel.unary_unary(
                '/analytics.AnalyticsService/GetUserJourney',
                request_serializer=analytics_dot_analytics__pb2.GetUserJourneyRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.GetUserJourneyResponse.FromString,
                _registered_method=True)
        self.GetSessionJourney = channel.unary_unary(
                '/analytics.AnalyticsService/GetSessionJourney',
                request_serializer=analytics_dot_analytics__pb2.GetSessionJourneyRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.GetSessionJourneyResponse.FromString,
                _registered_method=True)
        self.GetRegistrationStats = channel.unary_unary(
                '/analytics.AnalyticsService/GetRegistrationStats',
                request_serializer=analytics_dot_analytics__pb2.GetRegistrationStatsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.GetRegistrationStatsResponse.FromString,
                _registered_method=True)
        self.TrackVerificationRequest = channel.unary_unary(
                '/analytics.AnalyticsService/TrackVerificationRequest',
                request_serializer=analytics_dot_analytics__pb2.TrackVerificationRequestRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.TrackVerificationRequestResponse.FromString,
                _registered_method=True)
        self.MarkVerificationComplete = channel.unary_unary(
                '/analytics.AnalyticsService/MarkVerificationComplete',
                request_serializer=analytics_dot_analytics__pb2.MarkVerificationCompleteRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.MarkVerificationCompleteResponse.FromString,
                _registered_method=True)
        self.GetVerificationStatus = channel.unary_unary(
                '/analytics.AnalyticsService/GetVerificationStatus',
                request_serializer=analytics_dot_analytics__pb2.GetVerificationStatusRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__pb2.GetVerificationStatusResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrackStep(self, request, context):
        """Track a registration step interaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteStep(self, request, context):
        """Mark a step as completed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegistrationSteps(self, request, context):
        """Get all registration steps (reference data)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserJourney(self, request, context):
        """Get user's registration journey
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionJourney(self, request, context):
        """Get session's registration journey
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegistrationStats(self, request, context):
        """Get registration statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackVerificationRequest(self, request, context):
        """Verification tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkVerificationComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVerificationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackStep': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackStep,
                    request_deserializer=analytics_dot_analytics__pb2.TrackStepRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.TrackStepResponse.SerializeToString,
            ),
            'CompleteStep': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteStep,
                    request_deserializer=analytics_dot_analytics__pb2.CompleteStepRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.CompleteStepResponse.SerializeToString,
            ),
            'GetRegistrationSteps': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegistrationSteps,
                    request_deserializer=analytics_dot_analytics__pb2.GetRegistrationStepsRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.GetRegistrationStepsResponse.SerializeToString,
            ),
            'GetUserJourney': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserJourney,
                    request_deserializer=analytics_dot_analytics__pb2.GetUserJourneyRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.GetUserJourneyResponse.SerializeToString,
            ),
            'GetSessionJourney': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionJourney,
                    request_deserializer=analytics_dot_analytics__pb2.GetSessionJourneyRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.GetSessionJourneyResponse.SerializeToString,
            ),
            'GetRegistrationStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegistrationStats,
                    request_deserializer=analytics_dot_analytics__pb2.GetRegistrationStatsRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.GetRegistrationStatsResponse.SerializeToString,
            ),
            'TrackVerificationRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackVerificationRequest,
                    request_deserializer=analytics_dot_analytics__pb2.TrackVerificationRequestRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.TrackVerificationRequestResponse.SerializeToString,
            ),
            'MarkVerificationComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkVerificationComplete,
                    request_deserializer=analytics_dot_analytics__pb2.MarkVerificationCompleteRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.MarkVerificationCompleteResponse.SerializeToString,
            ),
            'GetVerificationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVerificationStatus,
                    request_deserializer=analytics_dot_analytics__pb2.GetVerificationStatusRequest.FromString,
                    response_serializer=analytics_dot_analytics__pb2.GetVerificationStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrackStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/TrackStep',
            analytics_dot_analytics__pb2.TrackStepRequest.SerializeToString,
            analytics_dot_analytics__pb2.TrackStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/CompleteStep',
            analytics_dot_analytics__pb2.CompleteStepRequest.SerializeToString,
            analytics_dot_analytics__pb2.CompleteStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegistrationSteps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetRegistrationSteps',
            analytics_dot_analytics__pb2.GetRegistrationStepsRequest.SerializeToString,
            analytics_dot_analytics__pb2.GetRegistrationStepsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserJourney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetUserJourney',
            analytics_dot_analytics__pb2.GetUserJourneyRequest.SerializeToString,
            analytics_dot_analytics__pb2.GetUserJourneyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionJourney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetSessionJourney',
            analytics_dot_analytics__pb2.GetSessionJourneyRequest.SerializeToString,
            analytics_dot_analytics__pb2.GetSessionJourneyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegistrationStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetRegistrationStats',
            analytics_dot_analytics__pb2.GetRegistrationStatsRequest.SerializeToString,
            analytics_dot_analytics__pb2.GetRegistrationStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackVerificationRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/TrackVerificationRequest',
            analytics_dot_analytics__pb2.TrackVerificationRequestRequest.SerializeToString,
            analytics_dot_analytics__pb2.TrackVerificationRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkVerificationComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/MarkVerificationComplete',
            analytics_dot_analytics__pb2.MarkVerificationCompleteRequest.SerializeToString,
            analytics_dot_analytics__pb2.MarkVerificationCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVerificationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetVerificationStatus',
            analytics_dot_analytics__pb2.GetVerificationStatusRequest.SerializeToString,
            analytics_dot_analytics__pb2.GetVerificationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
