# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/create_resource.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'resource/create_resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..auth import auth_pb2 as auth_dot_auth__pb2
from ..error import account_error_pb2 as error_dot_account__error__pb2
from ..resource import resource_category_pb2 as resource_dot_resource__category__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresource/create_resource.proto\x12\x10\x61\x63\x63ount.resource\x1a\x0f\x61uth/auth.proto\x1a\x19\x65rror/account_error.proto\x1a resource/resource_category.proto\"\xe2\x01\n\x15\x43reateResourceRequest\x12 \n\x04\x61uth\x18\x01 \x01(\x0b\x32\x12.account.auth.Auth\x12\x42\n\x08resource\x18\x02 \x01(\x0b\x32\x30.account.resource.CreateResourceRequest.Resource\x1a\x63\n\x08Resource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\".account.resource.ResourceCategory\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\xa2\x01\n\x16\x43reateResourceResponse\x12\x43\n\x08resource\x18\x01 \x01(\x0b\x32\x31.account.resource.CreateResourceResponse.Resource\x12+\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x1b.account.error.AccountError\x1a\x16\n\x08Resource\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.create_resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERESOURCEREQUEST']._serialized_start=131
  _globals['_CREATERESOURCEREQUEST']._serialized_end=357
  _globals['_CREATERESOURCEREQUEST_RESOURCE']._serialized_start=258
  _globals['_CREATERESOURCEREQUEST_RESOURCE']._serialized_end=357
  _globals['_CREATERESOURCERESPONSE']._serialized_start=360
  _globals['_CREATERESOURCERESPONSE']._serialized_end=522
  _globals['_CREATERESOURCERESPONSE_RESOURCE']._serialized_start=500
  _globals['_CREATERESOURCERESPONSE_RESOURCE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
