# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/resource_category.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'resource/resource_category.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n resource/resource_category.proto\x12\x10\x61\x63\x63ount.resource*\x94\x01\n\x10ResourceCategory\x12!\n\x1dRESOURCE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1e\n\x1aRESOURCE_CATEGORY_HARDWARE\x10\x01\x12\x1e\n\x1aRESOURCE_CATEGORY_SOFTWARE\x10\x02\x12\x1d\n\x19RESOURCE_CATEGORY_SERVICE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.resource_category_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCECATEGORY']._serialized_start=55
  _globals['_RESOURCECATEGORY']._serialized_end=203
# @@protoc_insertion_point(module_scope)
