
CREATE OR REPLACE TRIGGER app_user_registration_type_before_update_trigger
BEFORE UPDATE ON app_user_registration_type
FOR EACH ROW
EXECUTE FUNCTION app_user_registration_type_before_update_triggerfn();
