
CREATE OR REPLACE TRIGGER business_user_permission_role_before_update_trigger
BEFORE UPDATE ON business_user_permission_role
FOR EACH ROW
EXECUTE FUNCTION business_user_permission_role_before_update_triggerfn();
