/*
  FILENAME: new_version/registration-flow-client/src/api/analyticsService.js
  DESCRIPTION: This is the critical update. It now gets the session_id and
               user_id from storage *inside* the trackStep call, ensuring
               it always has the most recent data.
*/
import { grpcService } from './grpcService';
import { getAccessJwtFromStorage } from '../user-auth/authenticateUser';
// ✅ CHANGED: Import the official session manager
import { getOrCreateSessionId, getSessionId } from '../utils/sessionManager';

class AnalyticsService {
  constructor() {
    this.grpcService = grpcService;
    // ✅ CHANGED: Use the official session ID on initialization
    this.sessionId = getOrCreateSessionId();
  }

  // 🛑 REMOVED: getOrCreateSessionId (using imported one)
  // 🛑 REMOVED: generateUUID (using imported one)

  getUserId() {
    // ✅ CHANGED: Simplified to read from sessionStorage
    const userJson = sessionStorage.getItem('asante:user');
    if (userJson) {
      try {
        const user = JSON.parse(userJson);
        return user.id || null; // Return null if no ID
      } catch (e) {
        return null; // Return null on error
      }
    }
    return null; // Return null if no user
  }

  async trackStep(stepCode, previousStepCode = 0, nextStepCode = 0) {
    // ✅ CHANGED: getUserId() is now called *inside* trackStep
    // This ensures it gets the most up-to-date user ID from sessionStorage
    const userId = this.getUserId();
    const token = getAccessJwtFromStorage();
    
    try {
      // ✅ CHANGED: Get the session ID from the manager every time
      const currentSessionId = getSessionId() || this.sessionId;

      const response = await this.grpcService.trackStep(
        currentSessionId, // Pass the correct session ID
        userId,           // Pass the user ID (or null if not logged in)
        stepCode,
        previousStepCode,
        nextStepCode,
        token
      );
      
      // Store interaction ID for completing later
      const interaction = response.getInteraction();
      if (interaction && interaction.getId()) {
        sessionStorage.setItem(`asante:interactionId_${stepCode}`, interaction.getId());
      }
      
      return response;
    } catch (error) {
      // Silently fail - don't block user flow
      console.error('Analytics tracking error (non-blocking):', error);
      return null;
    }
  }

  async completeStep(stepCode, nextStepCode = 0) {
    const interactionId = sessionStorage.getItem(`asante:interactionId_${stepCode}`);
    
    if (!interactionId) {
      console.warn('No interaction ID found for step:', stepCode);
      return null;
    }

    const token = getAccessJwtFromStorage();

    try {
      const response = await this.grpcService.completeStep(
        interactionId,
        nextStepCode,
        token
      );
      
      return response;
    } catch (error) {
      // Silently fail - don't block user flow
      console.error('Analytics completion error (non-blocking):', error);
      return null;
    }
  }

  // --- METHODS FOR ANALYTICS DASHBOARD ---

  async getRegistrationSteps() {
    const token = getAccessJwtFromStorage();
    try {
      const response = await this.grpcService.getRegistrationSteps(token);
      // Convert proto list to plain JS object list
      return response.getStepsList().map(step => step.toObject());
    } catch (error) {
      console.error('Error fetching registration steps:', error);
      throw error;
    }
  }

  // --- THIS METHOD IS NOW FIXED ---
  async getRegistrationStats() {
    const token = getAccessJwtFromStorage();
    try {
      // FIXED: Pass undefined for startDate/endDate and token as the last arg
      const response = await this.grpcService.getRegistrationStats(undefined, undefined, token); 
      
      // FIXED: Get the 'stats' message from the response before converting
      const stats = response.getStats();
      
      return stats ? stats.toObject() : null;
    } catch (error) {
      console.error('Error fetching registration stats:', error);
      throw error;
    }
  }

 async getAllSessions() {
    const token = getAccessJwtFromStorage();
    try {
      // This calls the method we added to grpcService
      const sessionsListProto = await this.grpcService.getAllSessions(token);
      
      // Convert the list of proto messages into plain JS objects
      return sessionsListProto.map(session => {
        const sessionObj = session.toObject();
        
        // 🔧 FIX: Map 'categoriesList' (generated by proto) to 'categories' (expected by UI)
        // gRPC-Web appends 'List' to repeated fields when using toObject()
        sessionObj.categories = sessionObj.categoriesList || [];
        
        return sessionObj;
      });
    } catch (error) {
      console.error('Error fetching all sessions:', error);
      throw error;
    }
  }
  // --- END OF FIX ---


  // ---------------------------------------------

  // This function is no longer needed, as the logic is
  // now built into trackStep()
  // mapSessionToUser(userId) {}
}

const analyticsServiceInstance = new AnalyticsService();
export { analyticsServiceInstance as analyticsService };