"""
Analytics Schema - Registration Interaction Model

Logs all user actions within the registration workflow, including forward and 
backward navigation, with exact timing and sequencing.
"""

from sqlalchemy import Column, Integer, String, Text, TIMESTAMP, Index, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import uuid

from .base import Base


class RegistrationInteraction(Base):
    """
    Tracks every user interaction during the registration process.
    
    Key features:
    - Links to app_user (nullable for pre-signup tracking)
    - Uses session_id for anonymous tracking
    - Tracks previous/next steps for navigation analysis
    - Records exact timestamps for step_began_at and step_completed_at
    - Supports multi-session registration flows
    """
    __tablename__ = 'registration_interaction'
    __table_args__ = (
        # Index on app_user_id for user-specific queries
        Index('registration_interaction_app_user_idx', 'app_user_id'),
        
        # Index on registration_step_id for step-level analysis
        Index('registration_interaction_step_idx', 'registration_step_id'),
        
        # Partial index for completed steps only
        Index(
            'registration_interaction_completed_step_idx',
            'registration_step_id', 'step_completed_at',
            postgresql_where=Column('step_completed_at').isnot(None)
        ),
        
        # Partial index for incomplete steps (for dropout analysis)
        Index(
            'registration_interaction_incomplete_began_idx',
            'step_began_at',
            postgresql_where=Column('step_completed_at').is_(None)
        ),
        
        # Index on session_id for session-based queries
        Index('registration_interaction_session_idx', 'session_id'),
        
        # Composite partial index for incomplete steps by session
        Index(
            'registration_interaction_session_incomplete_idx',
            'session_id', 'registration_step_id',
            postgresql_where=Column('step_completed_at').is_(None)
        ),
        
        {'schema': 'analytics'}
    )
    
    # Primary key
    registration_interaction_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid()
    )
    
    # Foreign key to public.app_user (nullable for pre-signup users)
    app_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey('app_user.app_user_id', ondelete='SET NULL'),
        nullable=True
    )
    
    # Session ID generated by frontend
    session_id = Column(
        UUID(as_uuid=True),
        nullable=False
    )
    
    # Current registration step
    registration_step_id = Column(
        UUID(as_uuid=True),
        ForeignKey('analytics.registration_step.registration_step_id', ondelete='RESTRICT'),
        nullable=False
    )
    
    # Previous step (for navigation tracking)
    previous_step_id = Column(
        UUID(as_uuid=True),
        ForeignKey('analytics.registration_step.registration_step_id', ondelete='SET NULL'),
        nullable=True
    )
    
    # Next step (for navigation tracking)
    next_step_id = Column(
        UUID(as_uuid=True),
        ForeignKey('analytics.registration_step.registration_step_id', ondelete='SET NULL'),
        nullable=True
    )
    
    # Timestamp when user entered this step
    step_began_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.current_timestamp()
    )
    
    # Timestamp when user completed/left this step (nullable for current step)
    step_completed_at = Column(
        TIMESTAMP(timezone=True),
        nullable=True
    )
    
    # Standard timestamps
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.current_timestamp()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.current_timestamp(),
        onupdate=func.current_timestamp()
    )
    
    # Relationships (will need to be configured with proper back_populates)
    # registration_step = relationship("RegistrationStep", foreign_keys=[registration_step_id])
    # previous_step = relationship("RegistrationStep", foreign_keys=[previous_step_id])
    # next_step = relationship("RegistrationStep", foreign_keys=[next_step_id])
    
    def __repr__(self):
        return (f"<RegistrationInteraction("
                f"session={str(self.session_id)[:8]}, "
                f"step_id={str(self.registration_step_id)[:8]}, "
                f"began={self.step_began_at}, "
                f"completed={self.step_completed_at})>")
    
    def to_dict(self):
        """Convert to dictionary for API responses"""
        return {
            'registration_interaction_id': str(self.registration_interaction_id),
            'app_user_id': str(self.app_user_id) if self.app_user_id else None,
            'session_id': str(self.session_id),
            'registration_step_id': str(self.registration_step_id),
            'previous_step_id': str(self.previous_step_id) if self.previous_step_id else None,
            'next_step_id': str(self.next_step_id) if self.next_step_id else None,
            'step_began_at': self.step_began_at.isoformat() if self.step_began_at else None,
            'step_completed_at': self.step_completed_at.isoformat() if self.step_completed_at else None,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }
    
    @property
    def duration_seconds(self):
        """Calculate how long the user spent on this step"""
        if self.step_completed_at and self.step_began_at:
            return (self.step_completed_at - self.step_began_at).total_seconds()
        return None
    
    @property
    def is_completed(self):
        """Check if this step interaction is completed"""
        return self.step_completed_at is not None