# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error/account_error_code.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'error/account_error_code.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65rror/account_error_code.proto\x12\raccount.error*\xab\x02\n\x10\x41\x63\x63ountErrorCode\x12\x15\n\x11\x45RROR_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45RROR_INVALID_PARAMETER\x10\x01\x12\x1c\n\x18\x45RROR_RESOURCE_NOT_FOUND\x10\x02\x12\x1d\n\x19\x45RROR_INVALID_ENTITY_TYPE\x10\x03\x12\x1f\n\x1b\x45RROR_ENTITY_USER_NOT_FOUND\x10\x04\x12!\n\x1d\x45RROR_INVALID_PERMISSION_ROLE\x10\x05\x12\x1a\n\x16\x45RROR_OPERATION_FAILED\x10\x06\x12\"\n\x1e\x45RROR_EMAIL_ALREADY_REGISTERED\x10\n\x12\"\n\x1e\x45RROR_PARAMETER_MUST_BE_UNIQUE\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error.account_error_code_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTERRORCODE']._serialized_start=50
  _globals['_ACCOUNTERRORCODE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
