# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error/account_error.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'error/account_error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..error import account_error_code_pb2 as error_dot_account__error__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65rror/account_error.proto\x12\raccount.error\x1a\x1e\x65rror/account_error_code.proto\"S\n\x0c\x41\x63\x63ountError\x12\x33\n\nerror_code\x18\x01 \x01(\x0e\x32\x1f.account.error.AccountErrorCode\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error.account_error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTERROR']._serialized_start=76
  _globals['_ACCOUNTERROR']._serialized_end=159
# @@protoc_insertion_point(module_scope)
