# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/create_resource_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'resource/create_resource_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..resource import create_resource_pb2 as resource_dot_create__resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&resource/create_resource_service.proto\x12\x10\x61\x63\x63ount.resource\x1a\x1eresource/create_resource.proto2|\n\x15\x43reateResourceService\x12\x63\n\x0e\x43reateResource\x12\'.account.resource.CreateResourceRequest\x1a(.account.resource.CreateResourceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.create_resource_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERESOURCESERVICE']._serialized_start=92
  _globals['_CREATERESOURCESERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
