version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - '50051:50051'
    environment:
      - PYTHONPATH=/app/src
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=asante_dev
      - DB_PASSWORD=password
    command: python src/services/user/server.py
    networks:
      - asante-network
    depends_on:
      - postgres

  business-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-service
    ports:
      - '50052:50052'
    environment:
      - PYTHONPATH=/app/src
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=asante_dev
      - DB_PASSWORD=password
    command: python src/services/business/server.py
    networks:
      - asante-network
    depends_on:
      - postgres

  beneficiary-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beneficiary-service
    ports:
      - '50053:50053'
    environment:
      - PYTHONPATH=/app/src
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=asante_dev
      - DB_PASSWORD=password
    command: python src/services/beneficiary/server.py
    networks:
      - asante-network
    depends_on:
      - postgres

networks:
  asante-network:
    external: true
    name: asante-network
