# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error/user_error.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'error/user_error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from error import user_error_code_pb2 as error_dot_user__error__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65rror/user_error.proto\x12\nuser.error\x1a\x1b\x65rror/user_error_code.proto\"J\n\tUserError\x12-\n\nerror_code\x18\x01 \x01(\x0e\x32\x19.user.error.UserErrorCode\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error.user_error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERERROR']._serialized_start=67
  _globals['_USERERROR']._serialized_end=141
# @@protoc_insertion_point(module_scope)
