# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..auth import entity_type_pb2 as auth_dot_entity__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\x12\x0c\x61\x63\x63ount.auth\x1a\x16\x61uth/entity_type.proto\"\xb1\x01\n\x04\x41uth\x12%\n\x04user\x18\x01 \x01(\x0b\x32\x17.account.auth.Auth.User\x12)\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x19.account.auth.Auth.Entity\x1a\x12\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x1a\x43\n\x06\x45ntity\x12-\n\x0b\x65ntity_type\x18\x01 \x01(\x0e\x32\x18.account.auth.EntityType\x12\n\n\x02id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTH']._serialized_start=58
  _globals['_AUTH']._serialized_end=235
  _globals['_AUTH_USER']._serialized_start=148
  _globals['_AUTH_USER']._serialized_end=166
  _globals['_AUTH_ENTITY']._serialized_start=168
  _globals['_AUTH_ENTITY']._serialized_end=235
# @@protoc_insertion_point(module_scope)
