# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/get_user_by_email_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user/get_user_by_email_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..user import get_user_by_email_pb2 as user_dot_get__user__by__email__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$user/get_user_by_email_service.proto\x12\x11user.user_service\x1a\x1cuser/get_user_by_email.proto2~\n\x15GetUserByEmailService\x12\x65\n\x0eGetUserByEmail\x12(.user.user_service.GetUserByEmailRequest\x1a).user.user_service.GetUserByEmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.get_user_by_email_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERBYEMAILSERVICE']._serialized_start=89
  _globals['_GETUSERBYEMAILSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
