# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codegen.error import error_pb2 as error_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser/user.proto\x12\x04user\x1a\x11\x65rror/error.proto\"Q\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tuser_type\x18\x03 \x01(\t\x12\x1b\n\x13mailing_list_signup\x18\x04 \x01(\x08\"\x1f\n\x0eGetUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"I\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\x12\x1c\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x0c.error.Error\"R\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tuser_type\x18\x02 \x01(\t\x12\x1b\n\x13mailing_list_signup\x18\x03 \x01(\x08\"L\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\x12\x1c\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x0c.error.Error2\x86\x01\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=44
  _globals['_USER']._serialized_end=125
  _globals['_GETUSERREQUEST']._serialized_start=127
  _globals['_GETUSERREQUEST']._serialized_end=158
  _globals['_GETUSERRESPONSE']._serialized_start=160
  _globals['_GETUSERRESPONSE']._serialized_end=233
  _globals['_CREATEUSERREQUEST']._serialized_start=235
  _globals['_CREATEUSERREQUEST']._serialized_end=317
  _globals['_CREATEUSERRESPONSE']._serialized_start=319
  _globals['_CREATEUSERRESPONSE']._serialized_end=395
  _globals['_USERSERVICE']._serialized_start=398
  _globals['_USERSERVICE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
