name: user_manager

services:
  # User Services
  get_user_by_email:
    build:
      context: .
      dockerfile: ./src/features/user/get_user_by_email/Dockerfile
    image: user_manager_dev/get_user_by_email
    container_name: get_user_by_email
    ports:
      - "61000:61000"
    environment:
      - PYTHONPATH=/app
    networks:
      - asante-network
    profiles:
      - dev
      - test
      - user

networks:
  asante-network:
    external: true
    driver: bridge
    name: asante-network
