# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from codegen.business import business_pb2 as business_dot_business__pb2


class BusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusiness = channel.unary_unary(
                '/business.BusinessService/GetBusiness',
                request_serializer=business_dot_business__pb2.GetBusinessRequest.SerializeToString,
                response_deserializer=business_dot_business__pb2.GetBusinessResponse.FromString,
                )
        self.CreateBusiness = channel.unary_unary(
                '/business.BusinessService/CreateBusiness',
                request_serializer=business_dot_business__pb2.CreateBusinessRequest.SerializeToString,
                response_deserializer=business_dot_business__pb2.CreateBusinessResponse.FromString,
                )


class BusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusiness,
                    request_deserializer=business_dot_business__pb2.GetBusinessRequest.FromString,
                    response_serializer=business_dot_business__pb2.GetBusinessResponse.SerializeToString,
            ),
            'CreateBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBusiness,
                    request_deserializer=business_dot_business__pb2.CreateBusinessRequest.FromString,
                    response_serializer=business_dot_business__pb2.CreateBusinessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'business.BusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusiness',
            business_dot_business__pb2.GetBusinessRequest.SerializeToString,
            business_dot_business__pb2.GetBusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/CreateBusiness',
            business_dot_business__pb2.CreateBusinessRequest.SerializeToString,
            business_dot_business__pb2.CreateBusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
