# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: business/create_business_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'business/create_business_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codegen.business import create_business_pb2 as business_dot_create__business__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&business/create_business_service.proto\x12\x19\x62usiness.business_service\x1a\x1e\x62usiness/create_business.proto2\x8e\x01\n\x15\x43reateBusinessService\x12u\n\x0e\x43reateBusiness\x12\x30.business.business_service.CreateBusinessRequest\x1a\x31.business.business_service.CreateBusinessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business.create_business_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEBUSINESSSERVICE']._serialized_start=102
  _globals['_CREATEBUSINESSSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
