# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from codegen.business import get_business_pb2 as business_dot_get__business__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in business/get_business_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetBusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusiness = channel.unary_unary(
                '/business.business_service.GetBusinessService/GetBusiness',
                request_serializer=business_dot_get__business__pb2.GetBusinessRequest.SerializeToString,
                response_deserializer=business_dot_get__business__pb2.GetBusinessResponse.FromString,
                _registered_method=True)


class GetBusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetBusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusiness,
                    request_deserializer=business_dot_get__business__pb2.GetBusinessRequest.FromString,
                    response_serializer=business_dot_get__business__pb2.GetBusinessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'business.business_service.GetBusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('business.business_service.GetBusinessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetBusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/business.business_service.GetBusinessService/GetBusiness',
            business_dot_get__business__pb2.GetBusinessRequest.SerializeToString,
            business_dot_get__business__pb2.GetBusinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
