# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: business/get_business_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'business/get_business_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codegen.business import get_business_pb2 as business_dot_get__business__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#business/get_business_service.proto\x12\x19\x62usiness.business_service\x1a\x1b\x62usiness/get_business.proto2\x82\x01\n\x12GetBusinessService\x12l\n\x0bGetBusiness\x12-.business.business_service.GetBusinessRequest\x1a..business.business_service.GetBusinessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business.get_business_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBUSINESSSERVICE']._serialized_start=96
  _globals['_GETBUSINESSSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
