# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: business/get_business.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'business/get_business.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from codegen.error import user_error_pb2 as error_dot_user__error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62usiness/get_business.proto\x12\x19\x62usiness.business_service\x1a\x16\x65rror/user_error.proto\")\n\x12GetBusinessRequest\x12\x13\n\x0b\x62usiness_id\x18\x01 \x01(\t\"\xe2\x02\n\x13GetBusinessResponse\x12I\n\x08\x62usiness\x18\x01 \x01(\x0b\x32\x37.business.business_service.GetBusinessResponse.Business\x12%\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x15.user.error.UserError\x1a\xd8\x01\n\x08\x42usiness\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rbusiness_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x13\n\x0bwebsite_url\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\x12\x15\n\rlocation_city\x18\x06 \x01(\t\x12\x16\n\x0elocation_state\x18\x07 \x01(\t\x12\x0b\n\x03\x65in\x18\x08 \x01(\t\x12\x1c\n\x14\x62usiness_description\x18\t \x01(\t\x12\x15\n\rbusiness_size\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business.get_business_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBUSINESSREQUEST']._serialized_start=82
  _globals['_GETBUSINESSREQUEST']._serialized_end=123
  _globals['_GETBUSINESSRESPONSE']._serialized_start=126
  _globals['_GETBUSINESSRESPONSE']._serialized_end=480
  _globals['_GETBUSINESSRESPONSE_BUSINESS']._serialized_start=264
  _globals['_GETBUSINESSRESPONSE_BUSINESS']._serialized_end=480
# @@protoc_insertion_point(module_scope)
